<?php

/**
 * Implements of hook_menu().
 */
function sbadmin2_page_dashboard_menu() {
    return array(
        'dashboard' => array(
            'title' => 'Dashboard',
            'type' => MENU_NORMAL_ITEM,
            'page callback' => 'sbadmin2_page_dashboard_page_callback',
            'menu_name' => 'main-menu',
            'access callback' => 'user_is_logged_in',
            'file' => 'sbadmin2_page_dashboard.page.inc',
        ),
    );
}

/**
 * Implements of hook_theme().
 */
function sbadmin2_page_dashboard_theme($existing, $type, $theme, $path) {
    return array(
        'sbadmin2_page_dashboard' => array(
            'variables' => array(),
            'template' => 'sbadmin2-page-dashboard',
        ),
    );
}
