<?php

/**
 * Implements of hook_menu().
 */
function sbadmin2_page_template_01_menu() {
    return array(
        'template_01' => array(
            'title' => 'Template 01',
            'type' => MENU_NORMAL_ITEM,
            'page callback' => 'sbadmin2_page_template_01_page_callback',
            'menu_name' => 'main-menu',
            'access callback' => 'user_is_logged_in',
            'file' => 'sbadmin2_page_template_01.page.inc',
        ),
    );
}

/**
 * Implements of hook_theme().
 */
function sbadmin2_page_template_01_theme($existing, $type, $theme, $path) {
    return array(
        'sbadmin2_page_template_01' => array(
            'variables' => array(),
            'template' => 'sbadmin2-page-template-01',
        ),
    );
}
