<?php

/**
 * Implements of hook_menu().
 */
function sbadmin2_page_login_menu() {
    return array(
        'login' => array(
            'title' => 'Login',
            'type' => MENU_NORMAL_ITEM,
            'page callback' => 'sbadmin2_page_login_page_callback',
            'menu_name' => 'main-menu',
            'access callback' => 'user_is_logged_in',
            'file' => 'sbadmin2_page_login.page.inc',
        ),
    );
}

/**
 * Implements of hook_theme().
 */
function sbadmin2_page_login_theme($existing, $type, $theme, $path) {
    return array(
        'sbadmin2_page_login' => array(
            'variables' => array(),
            'template' => 'sbadmin2-page-login',
        ),
    );
}
