<?php
    
/**
 * Implements of hook_menu().
 */
function sbadmin2_page_chart_menu() {
    return array(
        'chart' => array(
            'title' => 'Chart',
            'type' => MENU_NORMAL_ITEM,
            'page callback' => 'sbadmin2_page_chart_page_callback',
            'menu_name' => 'main-menu',
            'access callback' => 'user_is_logged_in',
        ),
    );
}

function sbadmin2_page_chart_page_callback() {
    return 'addd';
}
