<?php

function sbadmin2_library_js_alter(&$javascript) {
    global $theme;
    if ($theme !== 'sbadmin2') {
        $path = drupal_get_path('module', 'sbadmin2_library');
        foreach ($javascript as $key => $value) {
            if (strpos($key, $path) === 0) {
                unset($javascript[$key]);
            }
        }
        return;
    }
}


function sbadmin2_library_css_alter(&$css) {
    global $theme;
    if ($theme !== 'sbadmin2') {
        $path = drupal_get_path('module', 'sbadmin2_library');
        foreach ($css as $key => $value) {
            if (strpos($key, $path) === 0) {
                unset($css[$key]);
            }
        }
        return;
    }
}
